language: node_js
node_js:
- '7'
- '8'
cache:
  directories:
  - node_modules
before_script:
- npm run travis
env:
  global:
  - secure: xGKT41g2ntScqxUP1PzVlIx/s8MIVwyDLK7D93exHSc3XuQ2/hEJB1WqoToDeW/40NSAjl4NCLQ918wLLCWnRtxkA8bp8JgqBDPYlbWLCHfyAqXhF5RpS8Yq//hAYTseiX/6q/ZsU9v+z7lofm2xm2dXgI8AlOXbSYH0XXt+WayZVqaueXnGizNQ1q1NgXEvCPYQVVf9FgkM/wfBUptbCp8qbKdrYA7nrz+69QZIECAO3asvMcVFRRuDV0BLTXELT+J9nCFMa/q1ygl6Qpy6UMQvDWnljXtyhGRnqyISX1okACEfStl5ic0oLc6hYJgbdkB4CXSdJG9C/j7of8dDZTRN2QhYqjygs+7kCNyYGh4w2/F1trxvnuoNCp4UJo33FOTiYE4Mq8HSB4F8ecB/fxXvG6PK1Ir7q9h+ECm55nohRMadTGVMPLekTvk5l3zpPjfCuAwei4rps2ayoOvF452zkqsRvc4cGPBVwnUGnohTYJjtiMt+9T9HWyU34QD8C8SHyp+ty+544f0TH7f3a8xBULGdcUPWuIYazUwf0RsomOLAzZAvqj9K+ok5/+P2johQAJRmitn+XtbhSLjcLHvqzcUisOkwdT5SnlsFJ3I1Dl2WS6SCko2Omaf2E3oZI+SIRkswSKCVGUum8lgQavVLo0DVTvA9CvlaXqXNxGU=
  - secure: n0tnMsGZZx+xVokW/jC3owFp+hP3XafqfLbgY/5AkFl4+ixKEz/9r8t1ykHjC4SkArNbaQHD4aS4udqQ8zguNUpX7LsoUOB85tKO6dnxXSFZTZ8IBAMs2YUfZaL2XHgnlZx4Dj7B7znnYNuqZECU/u13991HFeMM0XYd0r0GDDkRiy+WhOwt113xof8brqjj3XRCqn1eyOlHqPCcux+P8vGdietdPqLMolrksb4udF+gBHKu/bJUzwA0ALw9lIiUAQyyVkRVQp0rdHBU6WD1rX4Z3Jz5S4RECCQL1OPMpP6dbbvLZ3SX/iC2+/+OVDvfkfdyQ9EzjmopIPJLM8nhhvhl243rfJeUFyWTkaW3TMcFWu+QkYHvqmoRSIlABhhiwXwdeSqy37RzDX6LwVEiTqVN7yopthlaiTRVsSPT4HWGE10KUb6d3IKVE0PWdICPSDNvYrmf4Eip3Kp1/QhNhvqw9/JGEHUIoLAoUqwD+d3B0z8NFa/9K/jBrfOf7R4LSl5b/WZtWTDOTNtxJpvB81HHK7euyrnmQNTwMTXrZpr9k7jsYD703ClCwHh7HxjtjOZGD06Un2No7txlwMsUbmiMb6+9DDJCTP7sWbqMj3J/TWRib+dqbyyBeVsneOmCOaMJnYj1K4qmNCwKn+vhY1jacAf2ajlh/kxo1KuPvwE=
